# Generated by Django 4.0.2 on 2022-05-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationreport',
            name='student_id',
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.students'),
            preserve_default=False,
        ),
    ]
