# Generated by Django 4.0.2 on 2022-05-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_registrationreport_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitregistration',
            name='student_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Student.students'),
        ),
    ]
