# Generated by Django 4.0.2 on 2022-05-30 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_unitregistration_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitregistration',
            name='student_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
