# Generated by Django 4.0.1 on 2022-02-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_studentresult_onlineclassroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineclassroom',
            old_name='subject',
            new_name='subjects',
        ),
    ]
