# Generated by Django 4.0.2 on 2022-05-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_registrationreport_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclassroom',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
