# Generated by Django 4.0.2 on 2022-06-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_onlineclassroom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationreport',
            name='semester_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Student.semester'),
            preserve_default=False,
        ),
    ]
