# Generated by Django 4.0.2 on 2022-06-12 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_alter_attendance_session_year_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='staff_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
