# Generated by Django 4.0.2 on 2022-06-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0026_feedbackstaff_dept_id_feedbackstudent_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='dept_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Student.department'),
        ),
        migrations.AddField(
            model_name='leavereportstudent',
            name='dept_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Student.department'),
        ),
    ]
