# Generated by Django 4.0.2 on 2022-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0027_leavereportstaff_dept_id_leavereportstudent_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstaff',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='feedbackstudent',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
