# Generated by Django 4.0.2 on 2022-06-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0028_feedbackstaff_status_feedbackstudent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stage_id',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.SET_DEFAULT, to='Student.semester'),
        ),
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Student.courses'),
        ),
    ]
