# Generated by Django 4.0.2 on 2022-06-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0030_attendancereport_stage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='stage_id',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='Student.semester'),
        ),
    ]
