# Generated by Django 4.0.2 on 2022-06-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0035_unitregistration_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitregistration',
            name='session_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.sessionmodel'),
        ),
    ]
