# Generated by Django 4.0.2 on 2022-06-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0036_unitregistration_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationreport',
            name='dept_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.department'),
        ),
        migrations.AddField(
            model_name='registrationreport',
            name='session_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.sessionmodel'),
        ),
    ]
